jobs:
  deploy:
    name: "Deploy to EC2 ğŸ‰ğŸ¾"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout the files âœ…ğŸ›«ğŸ“‚"
        uses: actions/checkout@v2

      - name: "Deploy to server âš™â˜"
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          REMOTE_USER: ${{secrets.REMOTE_USER}}
          TARGET: ${{secrets.TARGET}}